import fs from 'fs/promises';
import path from 'path';
import PocketBase from 'pocketbase';
import { listMigrationFiles } from './helpers/file-system.js';
import { parseMigrationMeta } from './helpers/template.js';

/**
 * A single migration operation that can be executed through the REST API.
 *
 * Migration files generated by this MCP embed a metadata marker
 * (`// mcp-migration-meta: {...}`) describing their operations as plain
 * data, so apply/revert can be executed with `pb.collections.*` calls.
 *
 * Arbitrary JSVM migration files (e.g. created by the server-side
 * `./pocketbase migrate create`) use the server JSVM API (`migrate()`,
 * `new Collection()`, `app.findCollectionByNameOrId()`, `app.save()`) which
 * is NOT available to a REST client. They must be applied on the host with
 * `./pocketbase migrate up` and are reported with an explanatory error.
 */
interface MigrationOp {
    action: 'createCollection' | 'deleteCollection' | 'addField' | 'removeField';
    collection?: Record<string, any>;
    collectionIdOrName?: string;
    field?: Record<string, any>;
    fieldName?: string;
}

interface MigrationMeta {
    ops?: {
        up?: MigrationOp[];
        down?: MigrationOp[];
    };
}

const MANUAL_MIGRATION_HINT =
    'This migration file does not contain MCP metadata (it is a server-side JSVM migration). ' +
    'It cannot be executed through the REST client. Apply it on the PocketBase host with ' +
    '`./pocketbase migrate up` (see https://pocketbase.io/docs/js-migrations/).';

/**
 * Loads a migration file and returns its parsed MCP metadata.
 * @param migrationPath Full path to the migration file
 * @returns The parsed metadata, or null for manual JSVM migrations.
 */
async function loadMigrationMeta(migrationPath: string): Promise<MigrationMeta | null> {
    let content: string;
    try {
        content = await fs.readFile(migrationPath, 'utf-8');
    } catch (error: any) {
        throw new Error(`Failed to load migration file: ${error.message}`);
    }
    return parseMigrationMeta(content) as MigrationMeta | null;
}

/**
 * Executes a list of migration operations against the REST API.
 * @param ops Operations to execute, in order.
 * @param pb PocketBase instance (authenticated as superuser).
 */
async function executeOps(ops: MigrationOp[], pb: PocketBase): Promise<void> {
    for (const op of ops) {
        switch (op.action) {
            case 'createCollection': {
                if (!op.collection) {
                    throw new Error(`Invalid migration op: createCollection requires a collection definition.`);
                }
                await pb.collections.create(op.collection);
                break;
            }
            case 'deleteCollection': {
                if (!op.collectionIdOrName) {
                    throw new Error(`Invalid migration op: deleteCollection requires collectionIdOrName.`);
                }
                let collection;
                try {
                    collection = await pb.collections.getOne(op.collectionIdOrName);
                } catch (error: any) {
                    if (error?.status === 404) {
                        // Idempotent down: the collection is already gone
                        console.error(`deleteCollection: "${op.collectionIdOrName}" not found; skipping (already deleted).`);
                        break;
                    }
                    throw error;
                }
                await pb.collections.delete(collection.id);
                break;
            }
            case 'addField': {
                if (!op.collectionIdOrName || !op.field) {
                    throw new Error(`Invalid migration op: addField requires collectionIdOrName and field.`);
                }
                const collection = await pb.collections.getOne(op.collectionIdOrName);
                const fields: Record<string, any>[] = Array.isArray(collection.fields) ? [...collection.fields] : [];
                const fieldName = op.field.name;
                if (fields.some(f => f?.name === fieldName)) {
                    throw new Error(`Field "${fieldName}" already exists on collection "${collection.name}".`);
                }
                fields.push(op.field);
                await pb.collections.update(collection.id, { fields });
                break;
            }
            case 'removeField': {
                if (!op.collectionIdOrName || !op.fieldName) {
                    throw new Error(`Invalid migration op: removeField requires collectionIdOrName and fieldName.`);
                }
                let collection;
                try {
                    collection = await pb.collections.getOne(op.collectionIdOrName);
                } catch (error: any) {
                    if (error?.status === 404) {
                        // Idempotent down: the whole collection is already gone
                        console.error(`removeField: collection "${op.collectionIdOrName}" not found; skipping (already deleted).`);
                        break;
                    }
                    throw error;
                }
                const fields: Record<string, any>[] = Array.isArray(collection.fields) ? [...collection.fields] : [];
                const remaining = fields.filter(f => f?.name !== op.fieldName);
                if (remaining.length === fields.length) {
                    // Idempotent down: the field is already absent
                    console.error(`removeField: field "${op.fieldName}" not found on collection "${collection.name}"; skipping (already removed).`);
                    break;
                }
                await pb.collections.update(collection.id, { fields: remaining });
                break;
            }
            default:
                throw new Error(`Unknown migration op action: ${(op as any).action}`);
        }
    }
}

/**
 * Asserts the migration file exists and returns its metadata,
 * rejecting manual JSVM migrations with an explanatory error.
 */
async function loadExecutableMeta(migrationsDir: string, migrationFile: string): Promise<MigrationMeta> {
    const migrationPath = path.join(migrationsDir, migrationFile);

    // Check if file exists
    await fs.access(migrationPath, fs.constants.R_OK);

    const meta = await loadMigrationMeta(migrationPath);
    if (!meta) {
        throw new Error(`Cannot apply "${migrationFile}": ${MANUAL_MIGRATION_HINT}`);
    }
    return meta;
}

/**
 * Applies a specific migration
 * @param migrationFile Name of the migration file to apply
 * @param pb PocketBase instance
 * @param migrationsDir Directory containing migration files
 * @returns Result message
 */
export async function applyMigration(
    migrationFile: string,
    pb: PocketBase,
    migrationsDir: string
): Promise<string> {
    try {
        const meta = await loadExecutableMeta(migrationsDir, migrationFile);
        await executeOps(meta.ops?.up ?? [], pb);
        return `Successfully applied migration: ${migrationFile}`;
    } catch (error: any) {
        console.error(`Error applying migration ${migrationFile}:`, error);
        throw new Error(`Failed to apply migration: ${error.message}`);
    }
}

/**
 * Reverts a specific migration
 * @param migrationFile Name of the migration file to revert
 * @param pb PocketBase instance
 * @param migrationsDir Directory containing migration files
 * @returns Result message
 */
export async function revertMigration(
    migrationFile: string,
    pb: PocketBase,
    migrationsDir: string
): Promise<string> {
    try {
        const meta = await loadExecutableMeta(migrationsDir, migrationFile);
        await executeOps(meta.ops?.down ?? [], pb);
        return `Successfully reverted migration: ${migrationFile}`;
    } catch (error: any) {
        console.error(`Error reverting migration ${migrationFile}:`, error);
        throw new Error(`Failed to revert migration: ${error.message}`);
    }
}

/**
 * Applies all pending migrations
 * @param pb PocketBase instance
 * @param migrationsDir Directory containing migration files
 * @param appliedMigrations Array of already applied migration filenames
 * @returns Array of applied migration filenames
 */
export async function applyAllMigrations(
    pb: PocketBase,
    migrationsDir: string,
    appliedMigrations: string[] = []
): Promise<string[]> {
    try {
        // Get all migration files
        const allMigrations = await listMigrationFiles();

        // Filter out already applied migrations
        const pendingMigrations = allMigrations.filter(
            migration => !appliedMigrations.includes(migration)
        );

        if (pendingMigrations.length === 0) {
            return [];
        }

        const newlyApplied: string[] = [];

        // Apply each pending migration
        for (const migration of pendingMigrations) {
            await applyMigration(migration, pb, migrationsDir);
            newlyApplied.push(migration);
        }

        return newlyApplied;
    } catch (error: any) {
        console.error('Error applying all migrations:', error);
        throw new Error(`Failed to apply all migrations: ${error.message}`);
    }
}

/**
 * Reverts migrations up to a specific target
 * @param targetMigration Name of the migration to revert to (exclusive)
 * @param pb PocketBase instance
 * @param migrationsDir Directory containing migration files
 * @param appliedMigrations Array of already applied migration filenames
 * @returns Array of reverted migration filenames
 */
export async function revertToMigration(
    targetMigration: string,
    pb: PocketBase,
    migrationsDir: string,
    appliedMigrations: string[] = []
): Promise<string[]> {
    try {
        // If no migrations have been applied, nothing to revert
        if (appliedMigrations.length === 0) {
            return [];
        }

        // Sort applied migrations in reverse chronological order
        const sortedMigrations = [...appliedMigrations].sort((a, b) => {
            const tsA = parseInt(a.split('_')[0], 10);
            const tsB = parseInt(b.split('_')[0], 10);
            return tsB - tsA; // Descending order
        });

        const targetIndex = sortedMigrations.indexOf(targetMigration);
        if (targetIndex === -1 && targetMigration !== '') {
            throw new Error(`Target migration not found: ${targetMigration}`);
        }

        // Determine which migrations to revert
        const migrationsToRevert = targetMigration === ''
            ? sortedMigrations // Revert all if target is empty
            : sortedMigrations.slice(0, targetIndex);

        const reverted: string[] = [];

        // Revert each migration
        for (const migration of migrationsToRevert) {
            await revertMigration(migration, pb, migrationsDir);
            reverted.push(migration);
        }

        return reverted;
    } catch (error: any) {
        console.error('Error reverting migrations:', error);
        throw new Error(`Failed to revert migrations: ${error.message}`);
    }
}
